In [2]:
from automate import part_to_graph, PartFeatures, HetData
from torch_geometric.data import Batch
import torch
import os
import h5py
import pspy
import pandas as ps

## Testing flat batching

In [297]:
opts = pspy.PartOptions()

In [298]:
path = '/projects/grail/benjones/cadlab/data/models/b6c979cf4e6660ff81e5a9c2/67d2f776871477086fbc37c5/1520c99d5029db1cafd9d6e5/default/JHD.xt'
#path = '/projects/grail/benjones/cadlab/data/models/d8a598174bcbceaf7e2194e5/a54ba742eaa71cdd4dcefbaa/30babe4fe88353db54749ddc/default/JdD.xt'

In [299]:
part = pspy.Part(path, opts)

In [300]:
opts = PartFeatures()

In [301]:
pg = part_to_graph(part, opts)

In [302]:
part.summary.bounding_box

array([[-0.0085725, -0.016383 , -0.0035   ],
       [ 0.0085725,  0.0085725,  0.0012   ]])

In [194]:
datalist = [pg, pg]
batch = Batch.from_data_list(datalist, follow_batch=['mcfs'])

In [240]:
batch

Batch(E_to_edges=[3, 4608], F=[3, 5296], F_to_faces=[1, 5296], V=[2528, 3], V_to_vertices=[2, 72], batch=[686], edge_samples=[228, 7, 10], edge_to_flat_topos=[2, 228], edge_to_vertex=[2, 224], edges=[228, 68], face_samples=[102, 9, 10, 10], face_to_face=[3, 228], face_to_flat_topos=[2, 102], face_to_loop=[2, 284], faces=[102, 60], flat_topos=[686, 0], flat_topos_to_graph_idx=[1, 686], graph_idx=[2, 1], loop_to_edge=[2, 456], loop_to_flat_topos=[2, 284], loops=[284, 38], mcf_refs=[3, 1486], mcfs=[1486, 6], mcfs_batch=[1486], n_edges=[2], n_faces=[2], n_loops=[2], n_vertices=[2], part_feat=[2, 20], ptr=[3], vertex_to_flat_topos=[2, 72], vertices=[72, 3])

In [259]:
batch.graph_idx

tensor([[0],
        [0]])

In [196]:
[name for name in dir(batch) if name.endswith('batch')]

['batch', 'mcfs_batch']

In [197]:
pg_dict = {key: type((getattr(pg, key))) for key in dir(pg) if not isinstance(getattr(pg, key), torch.Tensor) and not callable(getattr(pg, key))}

In [198]:
batch_dict = {key: type((getattr(batch, key))) for key in dir(batch) if not isinstance(getattr(batch, key), torch.Tensor) and not callable(getattr(batch, key))}

In [199]:
set(pg_dict.keys()).difference(batch_dict.keys())

{'__edge_sets__', '__node_sets__', '__num_nodes__'}

In [200]:
set(batch_dict.keys()).difference(pg_dict.keys())

{'__cat_dims__',
 '__cumsum__',
 '__num_graphs__',
 '__num_nodes_list__',
 '__slices__',
 'num_graphs'}

In [201]:
set([key for key in dir(batch) if not callable(getattr(batch, key))]).difference(set(dir(pg)))

{'__cat_dims__',
 '__cumsum__',
 '__num_graphs__',
 '__num_nodes_list__',
 '__slices__',
 'batch',
 'mcfs_batch',
 'num_graphs',
 'ptr'}

In [202]:
batch.num_nodes

686

In [203]:
pg.__num_nodes__

343

In [204]:
batch.__num_nodes_list__

[343, 343]

In [205]:
batch.flat_topos_to_graph_idx

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0

In [206]:
def flatbatch(datalist):
    follow_batch = []
    if hasattr(datalist[0], 'mcfs'):
        follow_batch .append('mcfs')
    batch = Batch.from_data_list(datalist, follow_batch=follow_batch)
    data = HetData()
    for key in dir(batch):
        if not key.endswith('batch') and key != 'ptr':
            val = getattr(batch, key)
            if isinstance(val, torch.Tensor):
                setattr(data, key, val)
    data.__edge_sets__ = datalist[0].__edge_sets__
    if hasattr(batch, 'mcfs_batch'):
        data.mcf_to_graph_idx = batch.mcfs_batch.expand((1, batch.mcfs.shape[0]))
        data.__edge_sets__['mcf_to_graph_idx'] = len(datalist)
    data.__num_nodes__ = batch.num_nodes
    data.__node_sets__ = datalist[0].__node_sets__
    data.__edge_sets__['flat_topos_to_graph_idx'] = len(datalist)
    return data

In [207]:
fbatch = flatbatch(datalist)

In [208]:
set(fbatch.keys).difference(set(pg.keys))

{'mcf_to_graph_idx'}

In [209]:
fbatch.flat_topos_to_graph_idx

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0

In [210]:
fbatch.mcf_to_graph_idx

tensor([[0, 0, 0,  ..., 1, 1, 1]])

In [211]:
rebatch = Batch.from_data_list([fbatch, fbatch])

In [212]:
rebatch.flat_topos_to_graph_idx

tensor([[0, 0, 0,  ..., 3, 3, 3]])

In [213]:
rebatch.mcf_to_graph_idx.numpy()

array([[0, 0, 0, ..., 3, 3, 3]])

In [215]:
rebatch.flat_topos_to_graph_idx.shape

torch.Size([1, 1372])

In [214]:
rebatch.mcf_to_graph_idx.shape

torch.Size([1, 2972])

In [80]:
len(part.brep.nodes.faces) + len(part.brep.nodes.edges) + len(part.brep.nodes.loops) + len(part.brep.nodes.vertices)

343

## plotting

In [81]:
part.summary.bounding_box

array([[-0.0085725, -0.016383 , -0.0035   ],
       [ 0.0085725,  0.0085725,  0.0012   ]])

In [289]:
import meshplot as mp

In [304]:
pg.F.numpy().shape

(3, 2648)

In [305]:
part.mesh.F.shape

(2648, 3)

In [306]:
mp.plot(pg.V.numpy(), pg.F.numpy().T)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.00…

In [290]:
p = mp.plot(part.mesh.V, part.mesh.F)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.00…

In [84]:
p.add_mesh(part.mesh.V + 0.001, part.mesh.F)

1

In [85]:
import wildmeshing as wm

In [86]:
import igl

In [87]:
igl.write_obj('testobj.obj', part.mesh.V, part.mesh.F)

True

In [88]:
?wm.Tetrahedralizer

Docstring:      Wildmeshing tetrahedralizer
Init docstring: __init__(self: wildmeshing.wildmeshing.Tetrahedralizer, stop_quality: float = 10, max_its: int = 80, stage: int = 2, stop_p: int = -1, epsilon: float = 0.001, edge_length_r: float = 0.05, skip_simplify: bool = False) -> None
File:           /fast/jamesn8/anaconda3/envs/torch3/lib/python3.9/site-packages/wildmeshing/wildmeshing.cpython-39-x86_64-linux-gnu.so
Type:           pybind11_type
Subclasses:     


In [89]:
tet = wm.Tetrahedralizer()

TBB threads 32


In [90]:
?tet.set_mesh

Docstring:
set_mesh(self: wildmeshing.wildmeshing.Tetrahedralizer, V: numpy.ndarray[float64[m, n]], F: numpy.ndarray[int32[m, n]]) -> None

sets a mesh
Type:      method


In [91]:
tet.set_mesh(part.mesh.V * 100, part.mesh.F)

bbox_diag_length = 3.77454
ideal_edge_length = 0.188727
stage = 2
eps_input = 0.00377454
eps = 0.00208955
eps_simplification = 0.00167164
eps_coplanar = 3.77454e-06
dd = 0.00251636
dd_simplification = 0.00201309


In [ ]:
V, T = tet.get_tet_mesh()

In [68]:
part.default_mcfs[0].origin

array([0.0075725, 0.01524  , 0.       ])

In [58]:
data = torch.load('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/pspy_batches/batches/22533.dat')

In [62]:
data

HetData(E_to_edges=[3, 7434], F=[3, 7168], F_to_faces=[1, 7168], V=[3572, 3], V_to_vertices=[2, 784], edge_to_flat_topos=[2, 1299], edge_to_vertex=[2, 2474], edges=[1299, 68], face_to_face=[3, 1299], face_to_flat_topos=[2, 529], face_to_loop=[2, 617], faces=[529, 60], flat_topos=[3229, 0], flat_topos_to_graph_idx=[1, 3229], graph_idx=[3, 1], loop_to_edge=[2, 2598], loop_to_flat_topos=[2, 617], loops=[617, 38], mcf_refs=[3, 10325], mcfs=[10325, 6], n_edges=[3], n_faces=[3], n_loops=[3], n_vertices=[3], part_feat=[3, 20], vertex_to_flat_topos=[2, 784], vertices=[784, 3])

In [63]:
data.mcf_refs

tensor([[   0,    0,    0,  ..., 3204, 3205, 3206],
        [   0, 1451,  302,  ..., 3204, 3205, 3206],
        [   1,    7,    2,  ...,    3,    3,    3]])

In [105]:
from mechanical.utils import load_concatenated

In [106]:
load_concatenated?

Signature:
load_concatenated(
    stats_path,
    ext='.parquet',
    key=None,
    start='stats',
    drop_duplicates=True,
)
Docstring: <no docstring>
File:      /projects/grail/jamesn8/projects/mechanical/Mechanical/mechanical/utils/utils.py
Type:      function


In [116]:
batch_df = load_concatenated('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/pspy_batches',start='assembly_stats')
batch_df.fillna({'num_normalized_parts_with_discrepancies': 0,'num_invalid_transformed_parts':0}, inplace=True)

In [117]:
batch_df[lambda df: (df['num_normalized_parts_with_discrepancies'] == 0) & (df['num_invalid_transformed_parts'] == 0) & (df['initialized']) & (~df['too_big'])]

num_total_parts  num_invalid_loaded_parts  num_topologies  too_big  \
index                                                                       
45860               14                         0            1082    False   
45863                4                         0             613    False   
45872               11                         0            2011    False   
45873                7                         0             862    False   
45879                5                         0             660    False   
...                ...                       ...             ...      ...   
19260               12                         0            1476    False   
19264                2                         0             628    False   
19289                2                         0            1138    False   
19298                2                         0             165    False   
19301                5                         0            1166    False   

       invalid_bbox    maxdim  num_normalized_parts_with_discrepancies  \
index                                                                    
45860         False  0.217000                                      0.0   
45863         False  0.598122                                      0.0   
45872         False  0.260000                                      0.0   
45873         False  0.082000                                      0.0   
45879         False  0.142187                                      0.0   
...             ...       ...                                      ...   
19260         False  1.539875                                      0.0   
19264         False  0.103000                                      0.0   
19289         False  0.072000                                      0.0   
19298         False  0.077250                                      0.0   
19301         False  0.109886                                      0.0   

       num_invalid_transformed_parts  initialized  
index                                              
45860                            0.0         True  
45863                            0.0         True  
45872                            0.0         True  
45873                            0.0         True  
45879                            0.0         True  
...                              ...          ...  
19260                            0.0         True  
19264                            0.0         True  
19289                            0.0         True  
19298                            0.0         True  
19301                            0.0         True  

[13967 rows x 9 columns]

In [83]:
import numpy as np

In [174]:
f = h5py.File('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/new_axes/axis_data/552.hdf5','r')

In [175]:
np.array(f['mc_part_labels'])

array([0, 0, 0, ..., 6, 6, 6])

In [180]:
list(f['pair_data']['3,4']['axes'])

[]

In [97]:
list(f['pair_data']['0,1']['axes']['36'])

['indices']

In [87]:
[len(f['pair_data']['0,1']['axes'][ax]['indices']) for ax in f['pair_data']['0,1']['axes']]

[9, 9, 7]

In [99]:
f.close()

In [90]:
import meshplot as mp

In [158]:
dir_ind = 0
pair='7,9'
f = h5py.File('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/test_axis/axis_data/22.hdf5','r')
print(f['pair_data'].keys())
print(f['pair_data'][pair]['axes'].keys())
axis_cluster_indices = list(f['pair_data'][pair]['axes'][str(dir_ind)]['indices'])
axis_clusters = [np.array(f['dir_clusters'][str(dir_ind)]['axial_clusters'][str(ax)]) for ax in axis_cluster_indices]
axis_origins = np.vstack([np.array(f['mc_frames'][str(key)]['origins']) for key in range(len(f['mc_frames'].keys()))])
cluster_origins = [axis_origins[clust] for clust in axis_clusters]
for o, clust in zip(cluster_origins, axis_cluster_indices):
    print(clust)
    mp.plot(o, shading={"point_size": 0.125})
f.close()

<KeysViewHDF5 ['0,1', '0,10', '0,11', '0,14', '0,15', '0,16', '0,17', '0,18', '0,20', '0,4', '0,5', '0,6', '0,7', '0,9', '1,10', '1,11', '1,14', '1,15', '1,16', '1,17', '1,18', '1,20', '1,4', '1,5', '1,6', '1,7', '1,9', '10,11', '10,14', '10,15', '10,16', '10,17', '10,18', '10,20', '11,14', '11,15', '11,16', '11,17', '11,18', '11,20', '12,13', '12,15', '12,16', '12,17', '12,18', '12,19', '12,21', '13,15', '13,16', '13,17', '13,18', '13,19', '13,21', '14,15', '14,16', '14,17', '14,18', '14,20', '15,16', '15,17', '15,18', '15,19', '15,20', '15,21', '16,17', '16,18', '16,19', '16,20', '16,21', '17,18', '17,19', '17,20', '17,21', '18,19', '18,20', '18,21', '19,21', '2,12', '2,13', '2,15', '2,16', '2,17', '2,18', '2,19', '2,21', '2,3', '2,4', '2,5', '2,6', '2,7', '2,8', '3,12', '3,13', '3,15', '3,16', '3,17', '3,18', '3,19', '3,21', '3,4', '3,5', '3,6', '3,7', '3,8', '4,10', '4,11', '4,12', '4,13', '4,14', '4,15', '4,16', '4,17', '4,18', '4,19', '4,20', '4,21', '4,5', '4,6', '4,7', '4,8', '

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.1005957…

In [6]:
mate_check_df = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/new_axes_100groups_and_mate_check/mate_check_stats.parquet')

In [7]:
mate_check_df_old = ps.read_hdf('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/stats_check_mates_all_proposals_validate_rigidcomps_more_axis_stats/mate_stats_all.h5','mates')

In [9]:
mc_df = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/new_axes_100groups_and_mate_check/mc_stats.parquet')

In [41]:
mate_check_df['valid'].sum()/mate_check_df.shape[0]

0.9766936977204521

In [45]:
len(set(mate_check_df[lambda df: df['valid']]['Assembly']))/len(set(mate_check_df['Assembly']))

0.9999040859389987

In [10]:
mc_df[lambda df: (df['assembly'] == 552)]

dir_ind  axis_id  part1  part2          part1_occ          part2_occ  \
6025       15       18      0      4  MRPqM9QevOxx309ic  MiEfLhvfBX5+WwTK1   
6026       78       83      0      4  MRPqM9QevOxx309ic  MiEfLhvfBX5+WwTK1   
6027       15       18      0      6  MRPqM9QevOxx309ic  MtEBUiiw8jvjVvQLI   
6028       15       18      4      6  MiEfLhvfBX5+WwTK1  MtEBUiiw8jvjVvQLI   
6029       15       25      0      2  MRPqM9QevOxx309ic  M59OywwaIElzsyE8k   
...       ...      ...    ...    ...                ...                ...   
6110        0      230      2      5  M59OywwaIElzsyE8k  Mwuf6NDWDinzVdlEU   
6111        0      232      2      5  M59OywwaIElzsyE8k  Mwuf6NDWDinzVdlEU   
6112        0     1847      2      5  M59OywwaIElzsyE8k  Mwuf6NDWDinzVdlEU   
6113        0     1882      2      5  M59OywwaIElzsyE8k  Mwuf6NDWDinzVdlEU   
6114     4690     4736      3      4  M1/dZMrxY1lIcRFnx  MiEfLhvfBX5+WwTK1   

      num_MCs_1  num_MCs_2  assembly  
6025         93        162       552  
6026         18          2       552  
6027         93         48       552  
6028        162         48       552  
6029          4          4       552  
...         ...        ...       ...  
6110          5          2       552  
6111          5          1       552  
6112          2          1       552  
6113          2          2       552  
6114         61          3       552  

[90 rows x 9 columns]

In [11]:
mc_df[lambda df: (df['assembly'] == 552) & ((df['part2_occ'] == 'MiEfLhvfBX5+WwTK1') | (df['part1_occ'] == 'MiEfLhvfBX5+WwTK1'))]

dir_ind  axis_id  part1  part2          part1_occ          part2_occ  \
6025       15       18      0      4  MRPqM9QevOxx309ic  MiEfLhvfBX5+WwTK1   
6026       78       83      0      4  MRPqM9QevOxx309ic  MiEfLhvfBX5+WwTK1   
6028       15       18      4      6  MiEfLhvfBX5+WwTK1  MtEBUiiw8jvjVvQLI   
6070       15     8565      4      5  MiEfLhvfBX5+WwTK1  Mwuf6NDWDinzVdlEU   
6071       15     4864      4      5  MiEfLhvfBX5+WwTK1  Mwuf6NDWDinzVdlEU   
6072       15     4866      4      5  MiEfLhvfBX5+WwTK1  Mwuf6NDWDinzVdlEU   
6114     4690     4736      3      4  M1/dZMrxY1lIcRFnx  MiEfLhvfBX5+WwTK1   

      num_MCs_1  num_MCs_2  assembly  
6025         93        162       552  
6026         18          2       552  
6028        162         48       552  
6070          1          5       552  
6071          1          2       552  
6072          8          2       552  
6114         61          3       552

In [12]:
mate_check_df.loc[[9484]]

Assembly  dir_index  axis_index  has_any_axis  has_same_dir_axis  \
index                                                                     
9484        552       4690        4736          True               True   

           type  dirs_agree  axes_agree  valid  
index                                           
9484   REVOLUTE        True        True   True

In [15]:
mate_check_df['valid'].sum()/mate_check_df.shape[0]

0.9766936977204521

In [16]:
mate_check_df_old['valid'].sum()/mate_check_df_old.shape[0]

0.9836866866255269

In [164]:
mate_check_df[lambda df: ~df['valid']].index.intersection(mate_check_df_old[lambda df: ~df['valid']].index)

Int64Index([  18440,   18441,   18443,   18445,   22104,   22338,   23826,
              23835,   24933,   24934,
            ...
            1776653, 1779705, 1799958, 1808552, 1808553, 1811239, 1834292,
            1834295, 1850879, 1871943],
           dtype='int64', length=1055)

In [21]:
mate_check_df.loc[mate_check_df[lambda df: ~df['valid']].index.difference(mate_check_df_old[lambda df: ~df['valid']].index)][lambda df: df['type'] == 'FASTENED']['has_any_axis'].any()

False

In [22]:
mate_check_df_old[lambda df: ~df['valid']].index.difference(mate_check_df[lambda df: ~df['valid']].index)

Int64Index([    411,   24933,   24934,   24935,   24936,  111518,  114497,
             126606,  126607,  126609,
            ...
            1757158, 1765465, 1765468, 1788082, 1801535, 1816154, 1866974,
            1866975, 1879714, 1881987],
           dtype='int64', length=183)

In [31]:
actuallyvalid_old = mate_check_df_old[lambda df: df['valid']  & df['has_any_axis'] & ((df['type'] != 'SLIDER') | df['has_same_dir_axis'])].index.intersection(mate_check_df.index)

In [38]:
print('old valid:',len(actuallyvalid_old))
print('new valid:',mate_check_df[lambda df: df['valid']].shape[0])

old valid: 76252
new valid: 76480


In [39]:
mate_check_df_old.loc[actuallyvalid_old.difference(mate_check_df[lambda df: df['valid']].index)]

Assembly  dir_index  axis_index  has_any_axis  has_same_dir_axis  \
1457202     97005          0           0          True               True   
1457204     97005          0           0          True               True   
1457205     97005          0          -1          True               True   
1457206     97005          0          -1          True               True   

           type  dirs_agree  axes_agree  rigid_comp_attempting_motion  valid  
1457202  SLIDER        True        True                         False   True  
1457204  SLIDER        True        True                         False   True  
1457205  SLIDER        True        True                         False   True  
1457206  SLIDER        True        True                         False   True

In [37]:
mate_check_df.loc[actuallyvalid_old.difference(mate_check_df[lambda df: df['valid']].index)]

Assembly  dir_index  axis_index  has_any_axis  has_same_dir_axis  \
1457202     97005         48          -1         False              False   
1457204     97005         48          -1         False              False   
1457205     97005          0          -1         False              False   
1457206     97005          0          -1         False              False   

           type  dirs_agree  axes_agree  valid  
1457202  SLIDER        True        True  False  
1457204  SLIDER        True        True  False  
1457205  SLIDER        True        True  False  
1457206  SLIDER        True        True  False

In [281]:
mate_check_df_old.index.difference(mate_check_df.index)

Int64Index([   1030,    2033,    2361,    3263,    3420,    3588,    3973,
               7335,    7346,    7385,
            ...
            1877946, 1878124, 1878166, 1878254, 1878620, 1880144, 1880869,
            1881253, 1882294, 1882344],
           dtype='int64', length=3530)

In [242]:
newmate_df_new = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/new_augmented_mates/newmate_stats.parquet')

In [243]:
newmate_assembly_df_new = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/new_augmented_mates/assembly_stats.parquet')

In [249]:
bad_assemblies = newmate_assembly_df_new[lambda df: ~df['mc_counts_agree']].index
with open('data/dataset/assemblies_with_discrepant_mcs','w') as f:
    f.writelines([str(l) + '\n' for l in bad_assemblies])

In [250]:
newmate_df_new

part1                                part2  \
0      M6bbGpYeynYlaugVy                    MOioj+bH21Zqkx+em   
1      MJrVskG4U/7iIpIVh                    MtKznJtK5hTGijXbz   
2      MJrVskG4U/7iIpIVh                    MFT/jqXmTBLnGPukT   
3      M1IfORHnFC+1ltuRO                    Mo8s9oBgsM95bjDJi   
4      M1IfORHnFC+1ltuRO                    M61XDXFjhE+/RwYYp   
...                  ...                                  ...   
57114  MumOodeUesvG5ES8Q                    MVDWoZ5WBhkHUyX0e   
57115  MIFLWHuw7y7uxl6jt  MhqE5OBynbluOvpzg:Mhjf40Kd9jo9diwzi   
57116  MIFLWHuw7y7uxl6jt  MhqE5OBynbluOvpzg:Mrs4LkUzk6DVPBjqh   
57117  MIFLWHuw7y7uxl6jt  MhqE5OBynbluOvpzg:M2SrYDEsAEbFpklGu   
57118  MIFLWHuw7y7uxl6jt  MhqE5OBynbluOvpzg:MINKymPC4XmoUfv8z   

       num_dir_proposals  num_axes_proposals  added_mate  PIN_SLOT  BALL  \
0                      3                   7        True         0     0   
1                      1                   1        True         0     0   
2                      1                   1        True         0     0   
3                      1                   1        True         0     0   
4                      1                   1        True         0     0   
...                  ...                 ...         ...       ...   ...   
57114                  2                   1        True         0     0   
57115                  3                   4        True         0     0   
57116                  3                   1        True         0     0   
57117                  3                   1        True         0     0   
57118                  3                   1        True         0     0   

       PARALLEL  SLIDER  REVOLUTE  CYLINDRICAL  PLANAR  FASTENED  \
0             0       0         1            0       0         1   
1             0       0         0            2       0         0   
2             0       0         0            2       0         0   
3             0       0         0            2       0         0   
4             0       0         0            2       0         0   
...         ...     ...       ...          ...     ...       ...   
57114         0       0         2            0       0         0   
57115         0       1         0            0       0         2   
57116         0       1         0            0       0         3   
57117         0       1         0            0       0         3   
57118         0       1         0            0       0         3   

       chain_length         type  axis_index  dir_index  Assembly  
0                 2     REVOLUTE         514         -1        19  
1                 2  CYLINDRICAL           0         -1        22  
2                 2  CYLINDRICAL           0         -1        22  
3                 2  CYLINDRICAL           0         -1        22  
4                 2  CYLINDRICAL           0         -1        22  
...             ...          ...         ...        ...       ...  
57114             2     REVOLUTE           1         -1    125128  
57115             3       SLIDER          34         -1    125132  
57116             4       SLIDER          33         -1    125132  
57117             4       SLIDER          34         -1    125132  
57118             4       SLIDER          27         -1    125132  

[57119 rows x 18 columns]

In [256]:
labels_df = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/test_add_mate_labels/stats.parquet')
labels_df

skipped
index         
40        True

In [268]:
newmate_assembly_df_new[lambda df: ~df.isnull()][lambda df: ~df['mc_counts_agree']].index

Int64Index([   576,   1436,   2033,   4874,   6597,  11866,  13977,  16040,
             24996,  26742,  33827,  35134,  38704,  43593,  46779,  50409,
             53798,  55340,  56660,  61346,  61948,  69553,  74306,  74692,
             75207,  83369,  85275,  87066,  93489,  96922,  98376, 107807,
            110683, 112619, 113686, 118492, 120823, 121883, 122746],
           dtype='int64', name='index')

In [270]:
mate_check_assembly_df = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/new_axes_100groups_and_mate_check/assembly_stats.parquet')


In [271]:
mate_check_assembly_df

num_discrepant_mc_counts
index                           
19                             0
22                             0
26                             0
38                             0
45                             0
...                          ...
125098                         0
125100                         0
125126                         0
125128                         0
125132                         0

[10426 rows x 1 columns]

In [272]:
distance_df = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/new_distances/assembly_distance_stats.parquet')


In [274]:
distance_df.loc[47092]

num_total_parts                                   3
num_invalid_loaded_parts                          0
num_topologies                                   96
too_big                                       False
invalid_bbox                                  False
maxdim                                     0.096483
num_normalized_parts_with_discrepancies           0
num_invalid_transformed_parts                     0
initialized                                    True
num_degenerate_bboxes                             0
num_unconnected_close                             0
num_unconnected_coincident                        0
num_unconnected_close_and_coincident              0
num_connected_far                                 2
num_connected_not_coincident                      2
num_connected_far_or_not_coincident               2
Name: 47092, dtype: object

In [7]:
final_df = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/finalized_dataset_2/final_stat.parquet')

In [9]:
final_df_test = ps.read_parquet('/fast/jamesn8/assembly_data/assembly_torch2_fixsize/test_axis_and_check_and_augment/final_stat.parquet')

In [10]:
final_df_test

has_mate_check  attempted_augmentation  pspy_initialized  pspy_valid  \
index                                                                         
19               True                       1              True        True   
22               True                      15              True        True   
26               True                       9              True        True   
38               True                       3              True        True   
40               True                       0              True        True   
45               True                       1              True        True   
53               True                       4              True        True   
64               True                      36              True        True   
65               True                       1              True        True   
76               True                       1              True        True   

       all_mates_valid  has_torch_file  has_mc_file  has_all_distances  \
index                                                                    
19                True            True         True               True   
22                True            True         True               True   
26                True            True         True               True   
38                True            True         True               True   
40                True            True         True               True   
45                True            True         True               True   
53                True            True         True               True   
64                True            True         True               True   
65                True            True         True               True   
76                True            True         True               True   

       num_missing_mates  num_augmented_missing_mates  num_densified_fastens  \
index                                                                          
19                     0                            1                      0   
22                     6                           14                      0   
26                     9                            0                      0   
38                     2                            1                      0   
40                     0                            0                      0   
45                     0                            1                      0   
53                     3                            2                      0   
64                    16                           31                      0   
65                     2                            1                      0   
76                     3                            1                      0   

       has_all_type_labels  num_unconnected_close_with_axis  \
index                                                         
19                    True                                1   
22                    True                               20   
26                    True                                9   
38                    True                                3   
40                    True                                0   
45                    True                                1   
53                    True                                5   
64                    True                               47   
65                    True                                3   
76                    True                                4   

       num_connected_coaxial_far  valid  
index                                    
19                             0   True  
22                             0  False  
26                             2  False  
38                             0  False  
40                             0   True  
45                             1  False  
53                             0  False  
64                             2  False  
65                             

In [12]:
final_df

has_mate_check  attempted_augmentation  pspy_initialized  pspy_valid  \
index                                                                          
19                True                       1              True        True   
22                True                      15              True        True   
26                True                       9              True        True   
38                True                       3              True        True   
40                True                       0              True        True   
...                ...                     ...               ...         ...   
125100            True                       3              True        True   
125102            True                       0              True        True   
125126            True                       3              True        True   
125128            True                       1              True        True   
125132            True                       4              True        True   

        all_mates_valid  has_torch_file  has_mc_file  has_all_distances  \
index                                                                     
19                 True           False         True               True   
22                 True           False         True               True   
26                 True           False         True               True   
38                 True           False         True               True   
40                 True           False         True               True   
...                 ...             ...          ...                ...   
125100             True           False         True               True   
125102             True           False         True               True   
125126             True           False         True               True   
125128             True           False         True               True   
125132             True           False         True               True   

        num_missing_mates  num_augmented_missing_mates  num_densified_fastens  \
index                                                                           
19                      0                            1                      0   
22                      6                           14                      0   
26                      9                            0                      0   
38                      2                            1                      0   
40                      0                            0                      0   
...                   ...                          ...                    ...   
125100                  1                            2                      0   
125102                  0                            0                      0   
125126                  0                            3                      0   
125128                  0                            1                      0   
125132                  4                           10                      6   

        has_all_type_labels  num_unconnected_close_with_axis  \
index                                                          
19                     True                                1   
22                     True                               20   
26                     True                                9   
38                     True                                3   
40                     True                                0   
...                     ...                              ...   
125100                 True                                3   
125102                 True                                0   
125126                 True                                3   
125128                 True                                1   
125132                 True                               14   

        num_connected_coaxial_far  valid  
index                                     
19                

In [278]:
final_df[lambda df: (df['num_connected_coaxial_far'] == 0) & ((df['num_unconnected_close_with_axis'] == 0) | (df['num_augmented_missing_mates'] == df['num_unconnected_close_with_axis']))]

has_mate_check  attempted_augmentation  pspy_initialized  pspy_valid  \
index                                                                          
19                True                    True              True        True   
40               False                   False              True        True   
90               False                   False              True        True   
98                True                    True              True        True   
108               True                    True              True        True   
...                ...                     ...               ...         ...   
125093           False                   False              True        True   
125098            True                    True              True        True   
125102           False                   False              True        True   
125126            True                    True              True        True   
125128            True                    True              True        True   

        all_mates_valid  has_torch_file  has_mc_file  has_all_distances  \
index                                                                     
19                 True            True         True               True   
40                False            True         True               True   
90                False            True         True               True   
98                 True            True         True               True   
108                True            True         True               True   
...                 ...             ...          ...                ...   
125093            False            True         True               True   
125098             True            True         True               True   
125102            False            True         True               True   
125126             True            True         True               True   
125128             True            True         True               True   

        num_missing_mates  num_augmented_missing_mates  num_densified_fastens  \
index                                                                           
19                      0                            1                      0   
40                      0                            0                      0   
90                      0                            0                      0   
98                      0                            1                      0   
108                     0                           10                      4   
...                   ...                          ...                    ...   
125093                  0                            0                      0   
125098                  0                            5                      0   
125102                  0                            0                      0   
125126                  0                            3                      0   
125128                  0                            1                      0   

        has_all_type_labels  num_unconnected_close_with_axis  \
index                                                          
19                     True                                1   
40                    False                                0   
90                    False                                0   
98                     True                                1   
108                    True                               10   
...                     ...                              ...   
125093                False                                0   
125098                 True                                5   
125102                False                                0   
125126                 True                                3   
125128                 True                                1   

        num_connected_coaxial_far  valid  
index                                     
19                

In [287]:
mate_check_df_old[lambda df: df['Assembly'] == 90]

Assembly  dir_index  axis_index  has_any_axis  has_same_dir_axis  \
2033        90          1           0          True               True   

          type  dirs_agree  axes_agree  rigid_comp_attempting_motion  valid  
2033  REVOLUTE        True        True                         False   True