In [2]:
from pspart import Part
import meshplot as mp
import os
import numpy as np
import torch

In [3]:
datapath = '/projects/grail/benjones/cadlab'
part = Part(os.path.join(datapath, 'data/models/58aace5054540c1fba909bab/ac500a73d2324ea4fa3af589/84dd987436323f4357c873e2/default/JFD.xt'), uv_features=True)

In [7]:
part.bounding_box()

array([[-0.0635, -0.044 ,  0.    ],
       [ 0.0635,  0.044 ,  0.003 ]])

In [ ]:
data = torch.load('/projects/grail/jamesn8/0.pt')

In [30]:
(data.topo_type == 2).nonzero().shape

torch.Size([1124, 1])

In [33]:
data.crv_feat.shape

torch.Size([1126, 6, 10])

In [35]:
data.topo_type.shape

torch.Size([2889])

In [36]:
data

Batch(E2L=[2, 2248], F2F=[2, 1124], L2F=[2, 628], V2E=[2, 2036], batch=[2889], crv_feat=[1126, 6, 10], graph_idx=[1, 2889], idx=20, mc_pair_labels=[20000], mc_pair_type=[100000], mc_pairs=[6, 20000], mc_proposal_feat=[2, 100000], part_edges=[2, 57], part_pair_feats=[2, 57], ptr=[15], srf_feat=[493, 7, 10, 10], topo_type=[2889], x=[2889, 37])

In [37]:
#it's number 41

In [55]:
part = Part('/projects/grail/benjones/cadlab/data/models/d8a598174bcbceaf7e2194e5/a54ba742eaa71cdd4dcefbaa/30babe4fe88353db54749ddc/default/JdD.xt')

In [57]:
graph  = part.get_graph()

In [67]:
graph.T[graph.BB[:,5] > 1000000000]

array([0, 0, 0, 0], dtype=int32)

In [68]:
torch.from_numpy(graph.BB).float()[:,-3:]

tensor([[-0.1523,  0.1318,  0.0013],
        [-0.1157,  0.1245,  0.0013],
        [-0.1142,  0.1318,  0.0013],
        [-0.1460,  0.1269,  0.0000],
        [-0.1510,  0.1636,  0.0013],
        [-0.1215,  0.1318,  0.0381],
        [-0.1510,  0.1318,  0.0000],
        [-0.1523,  0.1245,  0.0000],
        [-0.1523,  0.1318,  0.0000],
        [-0.1510,  0.1623,  0.0000],
        [-0.1155,  0.1318,  0.0000],
        [    inf,     inf,     inf],
        [    inf,     inf,     inf],
        [-0.1523,  0.1623,  0.0013],
        [-0.1510,  0.1623,  0.0368],
        [-0.1155,  0.1623,  0.0013],
        [    inf,     inf,     inf],
        [    inf,     inf,     inf],
        [-0.1523,  0.1318,  0.0368],
        [-0.1155,  0.1318,  0.0368],
        [-0.1168,  0.1245,  0.0368],
        [-0.1523,  0.1318,  0.0368],
        [-0.1523,  0.1623,  0.0368],
        [-0.1523,  0.1623,  0.0368],
        [-0.1523,  0.1623,  0.0013],
        [-0.1142,  0.1318,  0.0368],
        [-0.1509,  0.1318,  0.0368],
 

In [74]:
from pytorch_lightning.metrics.metric import Metric


In [76]:
class RankingAccuracy(Metric):
    def __init__(
        self,
        compute_on_step: bool = True,
        dist_sync_on_step: bool = False,
    ):
        super().__init__(
            compute_on_step=compute_on_step,
            dist_sync_on_step=dist_sync_on_step,
        )


        self.add_state('ass', default=torch.tensor(0), dist_reduce_fx='mean')
    def update(self, value):
        self.ass += value
    def compute(self):
        return self.ass

In [77]:
rank = RankingAccuracy()

/fast/jamesn8/anaconda3/envs/torch3/lib/python3.9/site-packages/deprecate/deprecation.py:115: LightningDeprecationWarning: The `Metric` was deprecated since v1.3.0 in favor of `torchmetrics.metric.Metric`. It will be removed in v1.5.0.
  stream(template_mgs % msg_args)


In [78]:
rank

RankingAccuracy()

In [79]:
rank.compute()

/fast/jamesn8/anaconda3/envs/torch3/lib/python3.9/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: The ``compute`` method of metric RankingAccuracy was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)


tensor(0)

In [80]:
rank.update(3)

In [81]:
rank.compute()

tensor(3)

In [82]:
rank.update(4)

In [83]:
rank.compute()

tensor(7)

In [2]:
from enum import Enum

In [14]:
class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3
    def __str__(self):
        return self.name

In [16]:
print(Color.GREEN)

GREEN
